# Generated by Django 5.2.1 on 2025-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_members', models.IntegerField()),
                ('active_members_change_pct', models.IntegerField()),
                ('new_members_today', models.IntegerField()),
                ('new_members_change_pct', models.IntegerField()),
                ('avg_daily_attendance', models.IntegerField()),
                ('attendance_change_pct', models.IntegerField()),
                ('retention_rate_pct', models.IntegerField()),
                ('retention_change_pct', models.IntegerField()),
                ('top1_sport_name', models.CharField(max_length=100)),
                ('top1_sport_count', models.IntegerField()),
                ('top1_sport_pct', models.FloatField()),
                ('top2_sport_name', models.CharField(max_length=100)),
                ('top2_sport_count', models.IntegerField()),
                ('top2_sport_pct', models.FloatField()),
                ('top3_sport_name', models.CharField(max_length=100)),
                ('top3_sport_count', models.IntegerField()),
                ('top3_sport_pct', models.FloatField()),
                ('top1_attendance_hour', models.CharField(max_length=20)),
                ('top1_attendance_count', models.IntegerField()),
                ('top1_attendance_avg_hours', models.FloatField()),
                ('top2_attendance_hour', models.CharField(max_length=20)),
                ('top2_attendance_count', models.IntegerField()),
                ('top2_attendance_avg_hours', models.FloatField()),
                ('top3_attendance_hour', models.CharField(max_length=20)),
                ('top3_attendance_count', models.IntegerField()),
                ('top3_attendance_avg_hours', models.FloatField()),
                ('attendance_by_weekday', models.JSONField()),
                ('avg_hours_by_weekday', models.JSONField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
