# Generated by Django 5.2.1 on 2025-08-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataInsight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubstats',
            name='age_groups',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clubstats',
            name='membership_trends',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
