# Generated by Django 5.2.1 on 2025-08-13 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataInsight', '0002_clubstats_age_groups_clubstats_membership_trends'),
        ('UserModule', '0027_alter_genmember_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSubLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserModule.genmember')),
            ],
        ),
    ]
