# Generated by Django 5.2.1 on 2025-08-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataInsight', '0004_remove_clubstats_attendance_change_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubstats',
            name='avg_daily_attendance',
            field=models.FloatField(),
        ),
    ]
