# Generated by Django 5.2.1 on 2025-08-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataInsight', '0005_alter_clubstats_avg_daily_attendance'),
        ('UserModule', '0028_sport_alter_genmember_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubstats',
            name='top1_sport_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top1_clubstats', to='UserModule.sport'),
        ),
        migrations.AlterField(
            model_name='clubstats',
            name='top2_sport_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top2_clubstats', to='UserModule.sport'),
        ),
        migrations.AlterField(
            model_name='clubstats',
            name='top3_sport_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top3_clubstats', to='UserModule.sport'),
        ),
    ]
