# Generated by Django 5.2.1 on 2025-08-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataInsight', '0007_remove_clubstats_top1_attendance_avg_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubstats',
            name='avg_hours_by_weekday',
        ),
    ]
