version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DB_NAME=gym_db
      - DB_USER=postgres
      - DB_PASSWORD=Qx9!7rL#2VpGz$Nw
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gym_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qx9!7rL#2VpGz$Nw
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kazemianaryan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Qx9!7rL#2VpGz$Nw
    depends_on:
      - db

volumes:
  pgdata:
