# Generated by Django 5.2.1 on 2025-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('total_steps', models.IntegerField(default=0)),
                ('current_step', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
