# Generated by Django 5.2.1 on 2025-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0020_genmember_couch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genmember',
            old_name='section_left',
            new_name='session_left',
        ),
        migrations.AddField(
            model_name='genmember',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genmember',
            name='sport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
