# Generated by Django 5.2.1 on 2025-07-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0021_rename_section_left_genmember_session_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmember',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
