# Generated by Django 5.2.1 on 2025-07-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0022_genmember_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmember',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserModule.genmembershiptype'),
        ),
    ]
