# Generated by Django 5.2.1 on 2025-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0023_genmember_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmember',
            name='is_single_settion',
            field=models.BooleanField(default=False),
        ),
    ]
