# Generated by Django 5.2.1 on 2025-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0024_genmember_is_single_settion'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmember',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
