# Generated by Django 5.2.1 on 2025-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0025_genmember_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmember',
            name='last_change_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
