# Generated by Django 5.2.1 on 2025-08-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0026_genmember_last_change_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genmember',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
