# Generated by Django 5.2.1 on 2025-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0028_sport_alter_genmember_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genperson',
            name='birth_date',
            field=models.DateField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='genperson',
            name='thumbnail_image',
            field=models.BinaryField(null=True),
        ),
    ]
