# Generated by Django 5.2.1 on 2025-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0029_alter_genperson_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
