# Generated by Django 5.2.1 on 2025-08-20 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0029_alter_genperson_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuser',
            name='access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='secuser',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secuser',
            name='lincess',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CoachManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachName', models.CharField(max_length=255)),
                ('coachPhoneNum', models.CharField(max_length=20)),
                ('coachNormalPlanPrice', models.PositiveIntegerField()),
                ('coachPrivatePlanPrice', models.PositiveIntegerField()),
                ('coachShift', models.CharField(max_length=50)),
                ('coachNormalUser', models.PositiveIntegerField(default=0)),
                ('coachPrivateUser', models.PositiveIntegerField(default=0)),
                ('coachSport', models.ManyToManyField(related_name='coaches', to='UserModule.sport')),
            ],
        ),
    ]
