# Generated by Django 5.2.1 on 2025-08-17 17:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0030_sport_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachManagement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coachId', models.CharField(max_length=50, unique=True)),
                ('coachName', models.CharField(max_length=255)),
                ('coachPhoneNum', models.CharField(max_length=20)),
                ('coachSport', models.JSONField(default=list)),
                ('coachNormalPlanPrice', models.PositiveIntegerField()),
                ('coachPrivatePlanPrice', models.PositiveIntegerField()),
                ('coachShift', models.CharField(max_length=50)),
                ('coachNormalUser', models.PositiveIntegerField(default=0)),
                ('coachPrivateUser', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='secuser',
            name='access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='secuser',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secuser',
            name='lincess',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
