# Generated by Django 5.2.1 on 2025-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0030_secuser_access_secuser_is_vip_secuser_lincess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachmanagement',
            name='coachNormalUser',
        ),
        migrations.RemoveField(
            model_name='coachmanagement',
            name='coachPrivateUser',
        ),
        migrations.AddField(
            model_name='coachmanagement',
            name='coach_users',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
