# Generated by Django 5.2.1 on 2025-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0031_coachmanagement_secuser_access_secuser_is_vip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachmanagement',
            name='coachId',
        ),
        migrations.RemoveField(
            model_name='coachmanagement',
            name='coachSport',
        ),
        migrations.AlterField(
            model_name='coachmanagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='coachmanagement',
            name='coachSport',
            field=models.ManyToManyField(related_name='coaches', to='UserModule.sport'),
        ),
    ]
