# Generated by Django 5.2.1 on 2025-08-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0031_remove_coachmanagement_coachnormaluser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachmanagement',
            name='coach_users',
        ),
        migrations.CreateModel(
            name='CoachUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('subscription_end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_users', to='UserModule.coachmanagement')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_members', to='UserModule.genperson')),
            ],
        ),
    ]
