# Generated by Django 5.2.1 on 2025-09-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0032_remove_coachmanagement_coach_users_coachusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachusers',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachusers',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coachusers',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachusers',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
