# Generated by Django 5.2.1 on 2025-09-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0033_alter_coachusers_end_time_alter_coachusers_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachusers',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coachusers',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
