# Generated by Django 5.2.1 on 2025-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreModule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
