# Generated by Django 5.2.1 on 2025-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreModule', '0003_remove_order_barcode_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
