# Generated by Django 5.2.1 on 2025-08-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreModule', '0004_remove_orderitem_note_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
