# Generated by Django 5.2.1 on 2025-07-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LockerModule', '0003_alter_locker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
