# Generated by Django 5.2.1 on 2025-09-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LockerModule', '0006_saloon_alter_locker_locker_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
