# Generated by Django 5.1.6 on 2025-02-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0003_alter_gympayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gympayment',
            name='is_first_save',
        ),
        migrations.RemoveField(
            model_name='gymuserpayment',
            name='is_first_save',
        ),
    ]
