# Generated by Django 5.1.6 on 2025-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0004_remove_gympayment_is_first_save_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='day_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymuserpayment',
            name='subscription_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
