# Generated by Django 5.1.6 on 2025-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0005_gymuser_day_left_gymuserpayment_subscription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_day_lef',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='day_left',
            field=models.IntegerField(default=0),
        ),
    ]
