# Generated by Django 5.1.6 on 2025-02-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0006_user_use_day_lef_alter_gymuser_day_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gym_manager',
            field=models.BooleanField(default=True),
        ),
    ]
