# Generated by Django 5.1.6 on 2025-02-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0007_user_is_gym_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='use_day_lef',
            new_name='use_day_left',
        ),
    ]
