# Generated by Django 5.1.6 on 2025-02-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0008_rename_use_day_lef_user_use_day_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gym-images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='locker_count',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_locker_count',
            field=models.IntegerField(default=20),
        ),
    ]
