# Generated by Django 5.1.6 on 2025-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0009_user_image_user_locker_count_user_vip_locker_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuserpayment',
            name='payment_method',
            field=models.CharField(choices=[('card-to-card', 'card to card'), ('cash', 'cash'), ('pos_machine', 'pos machine')], default='pos_machine', max_length=20),
        ),
        migrations.AddField(
            model_name='gymuserpayment',
            name='payment_state',
            field=models.CharField(choices=[('paid', 'paid'), ('waiting', 'waiting'), ('not-paid', 'not paid')], default='waiting', max_length=20),
        ),
    ]
