# Generated by Django 5.1.6 on 2025-02-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0010_gymuserpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='user_state',
            field=models.CharField(choices=[('vip', 'vip'), ('normal', 'normal')], default='vip', max_length=40),
        ),
    ]
