# Generated by Django 5.1.6 on 2025-02-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0011_gymuser_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='biometric_type',
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_type',
            field=models.CharField(choices=[('finger_print', 'finger print'), ('face_scan', 'face scan')], default='finger_print', max_length=40),
        ),
    ]
