# Generated by Django 5.1.6 on 2025-03-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0012_remove_gymuser_biometric_type_user_biometric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='locker_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='started_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
