# Generated by Django 5.1.6 on 2025-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0013_gymuser_family_gymuser_locker_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='face_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
