# Generated by Django 5.1.6 on 2025-03-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0016_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
