# Generated by Django 5.1.6 on 2025-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0018_alter_gymuser_day_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='vip_locker_numbers',
            field=models.ManyToManyField(blank=True, null=True, to='GymModule.viplocker'),
        ),
    ]
