# Generated by Django 5.1.6 on 2025-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymModule', '0019_viplocker_user_vip_locker_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuserpayment',
            name='payed_amount',
            field=models.IntegerField(),
        ),
    ]
