# Generated by Django 5.2.1 on 2025-07-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentModule', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
