# Generated by Django 5.2.1 on 2025-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=100)),
                ('deviceType', models.CharField(max_length=200)),
                ('deviceGroup', models.CharField(max_length=100)),
                ('deviceName', models.CharField(max_length=100)),
                ('devicePort', models.CharField(max_length=100)),
                ('deviceIP', models.CharField(max_length=100)),
                ('baudRate', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('dataBits', models.CharField(max_length=100)),
                ('stopBits', models.CharField(max_length=100)),
                ('timeout', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
            ],
        ),
    ]
